class_name SavedPlayerData
extends SavedData

@export var character_id:int
@export var character_traits:Dictionary
@export var inventory_data:Dictionary
@export var naked_gear:Dictionary
@export var quest_requirements_tracking:Dictionary
@export var skills_data:Dictionary
@export var equipment_data:Dictionary
@export var player_stats:Dictionary
@export var equipment_stats:Dictionary
@export var quest_data:Dictionary
@export var loaded_skills:Dictionary
@export var user_name:String
@export var profession:String
@export var stat_points:int
@export var skill_points:int
@export var health:int
@export var mana:int
@export var autoAttacking:bool
@export var skill_Knight:bool
@export var skill_Ninja:bool
@export var skill_1A:bool
@export var skill_1B:bool
@export var skill_2A:bool
@export var skill_2B:bool
@export var skill_2C:bool
@export var skill_2D:bool
@export var skill_3A:bool
@export var skill_3B:bool
@export var skill_4A:bool
@export var skill_4B:bool
@export var rate_of_fire:int
@export var gold:int
@export var curXp:int
@export var xpToNextLevel:int
@export var interactDist:int
@export var attackDist:int
@export var ranged_auto:bool
